org: kizza
app: happy-singing-kids
service: frontend

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  stackName: ${self:app}-${self:service}-${self:provider.stage}

plugins:
  - serverless-lift

# stages: Use stages when using version 4
custom:
  dev:
    params:
      domain:
        - dev.happysingingkids.com

  prod:
    params:
      domain:
        - happysingingkids.com
        - www.happysingingkids.com

constructs:
  react:
    type: static-website
    path: out
    domain: ${self:custom.${self:provider.stage}.params.domain}
    redirectToMainDomain: true
    certificate: arn:aws:acm:us-east-1:373532833815:certificate/e939d16b-4dfd-45d9-a1c1-697a299f29d7

resources:
  # Use stackName for automatic outputs (to avoid service-stage class with other apps)
  Outputs:
    ServerlessDeploymentBucketName:
      Export:
        Name: ${self:provider.stackName}-ServerlessDeploymentBucketName
